/** @format */
const work = [
	{
		id: '05',
		institution: 'parcelLab GmbH, München',
		role: 'Junior Technical Support Engineer',
		startDate: 'Sept. 2023',
		endDate: 'Sept. 2024',
		taskTitle: 'Summary of task and responsabilities.',
		url: 'https://www.parcel-lab.de/',
		tasks: [
			'Served as primary point of contact for B2B clients, efficiently resolving technical issues and optimizing customer communications through HTML and JavaScript customizations.',
			'Collaborated with cross-functional teams to implement product improvements and provide technical guidance on solution optimization.',
			'Contributed to team growth by training new support engineers and maintaining technical documentation for best practices.',
			'Utilized technical tools including Zendesk, Jira, and Git while managing client requests and operational tasks.',
		],
	},
	{
		id: '04',
		institution: 'Münchner Volkshochschule, München',
		role: 'Spanish Teacher',
		startDate: '2020',
		endDate: '2023',
		taskTitle: 'Summary of responsabilities in each institution',
		tasks: [
			'Implement online learning platforms (e.g. Moodle) and video conferencing tools to enable interactive distance learning.',
			"Work collaboratively with other teachers to create extracurricular activities and practice opportunities to enrich students' Spanish proﬁciency.",
			"Analyze, develop and manage customized learning plans tailored to each student's needs to help them achieve their level of Spanish proﬁciency.",
			'Participate in regular professional development to expand my pedagogical toolkit and incorporate new trends into language instruction.',
		],
	},
	{
		id: '03',
		institution: 'Hochschule München, München',
		role: 'Spanish Teacher',
		startDate: '2018',
		endDate: '2023',
		taskTitle: '',
		tasks: [],
	},
	{
		id: '02',
		institution: 'Ludwig-Maximilians-University, München',
		role: 'Spanish Teacher',
		startDate: '2017/06',
		endDate: '2020/02',
		taskTitle: '',
		tasks: [],
	},
	{
		id: '01',
		institution: 'Passau University, Passau',
		role: 'Spanish Teacher',
		startDate: '2008/04',
		endDate: '2016/07',
		taskTitle: '',
		tasks: [],
	},
];
const education = [
	{
		id: '04',
		institution: 'IRONHACK Cooding School, Spain',
		role: 'JavaScript Web Development MERN stack',
		startDate: '2020/11',
		endDate: '2021/03',
		taskTitle: '',
		url: 'https://www.credential.net/15974796-8ca4-4a1e-b017-84187771660f#gs.3nnm8f',
		tasks: [
			'Intensive 6-month web development bootcamp focused on core frontend, backend, and database technologies',
			'Develop front-end applications using the following technologies: HTML5, CSS3, JavaScript, Responsive Web Design & React',
			'Back-end applications using technologies and techniques: and NodeJS, ExpressJS, REST APIs, MongoDB and Server-Side Rendering',
			'Write queries in MongoDB to extract information from databases and manipulate data: set up the database, implement CRUD actions, and reference documents',
			'Create schemas and data models for the MongoDB database using an ODM',
			'Integrate the third-party services (APIs) with an existing front-end or back-end JavaScript application',
			'Use Command line, Git version control, GitHub, and Gitflow branching model to manage projects',
			'Deploy front-end and back-end applications to a Cloud Services: Netlify, Heroku, GitHub Pages, Render',
			'Write clean, modular, and efficient code following best practices (KISS, YAGNI, DRY & SOC)',
			'Use Agile & Lean as frameworks for product management: stand-ups, retros, values, Kanban, MVP to ensure good collaboration and workflow',
		],
		active: 'true',
	},
	{
		id: '03',
		institution: 'Bayerischer Volkshochschulverband e.V., Munich',
		role: 'Eurolta instructor certificate ',
		startDate: '2020/11',
		endDate: '2021/03',
		taskTitle: '',
		url: '',
		tasks: [
			'Solid knowledge of the Common European Framework of Reference (CEFR) for learning foreign languages',
			'Ability to formulate learning objectives and plan communicative, action-oriented language course contents',
			'50 hours of in-person and online class instruction plus 50 hours of self-study',
		],
		active: 'true',
	},
	{
		id: '02',
		institution: 'Technical University of Ambato, Ecuador',
		role: 'Clinical Psychology Degree ',
		startDate: '2000/09',
		endDate: '2006/11',
		taskTitle: '',
		url: '',
		tasks: ['Officially validated as B.A.+ Degree', 'German grade: 1.5', 'English grade: A-'],
		active: 'true',
	},
	{
		id: '01',
		institution: "'Guayaquil' Technical High School, Ecuador",
		role: 'Industrial Diploma in electronics',
		startDate: '1989/07',
		endDate: '1995/06',
		taskTitle: '',
		url: '',
		tasks: [],
		active: 'true',
	},
];
const skills = {
	frontend: [
		{
			id: '01',
			name: 'HTML5',
			icon: 'ImHtmlFive',
			level: '★★★★☆',
		},
		{
			id: '02',
			name: 'CSS3',
			icon: 'ImCss3',
			level: '★★★★☆',
		},
		{
			id: '03',
			name: 'JavaScript',
			icon: 'IoLogoJavascript',
			level: '★★★☆☆',
		},
		{
			id: '04',
			name: 'ReactJS',
			icon: 'SiReact',
			level: '★★★☆☆',
		},
		{
			id: '05',
			name: 'TypeScript',
			icon: 'SiTypescript',
			level: '★★☆☆☆',
		},
		{
			id: '06',
			name: 'Responsive Design',
			icon: 'VscEditorLayout',
			level: '★★★☆☆',
		},
		{
			id: '07',
			name: 'Redux',
			icon: 'SiRedux',
			level: '★☆☆☆☆',
		},
	],
	backend: [
		{
			id: '01',
			name: 'NodeJS',
			icon: 'IoLogoNodejs',
			level: '★★☆☆☆',
		},

		{
			id: '02',
			name: 'ExpressJS',
			icon: 'SiExpress',
			level: '★★☆☆☆',
		},
		{
			id: '03',
			name: 'MongoDB',
			icon: 'SiMongodb',
			level: '★★☆☆☆',
		},
	],
	tools: [
		{
			id: '01',
			name: 'Git',
			icon: 'SiGit',
			level: '★★★☆☆',
		},
		{
			id: '02',
			name: 'GitHub',
			icon: 'SiGithub',
			level: '★★★☆☆',
		},

		{
			id: '03',
			name: 'Pnpm',
			icon: 'SiPnpm',
			level: '★★★☆☆',
		},
		{
			id: '04',
			name: 'Sketch',
			icon: 'SiSketch',
			level: '★★☆☆☆',
		},
		{
			id: '05',
			name: 'VSCode',
			icon: 'SiVisualstudiocode',
			level: '★★★★☆',
		},
	],
};
export { work, education, skills };
